default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432
  pool: 5
  host: localhost

development:
  <<: *default
  database: pg_app_development
  username: postgres
  password: psql

test:
  <<: *default
  database: pg_app_test
  username: postgres
  password: psql
  